# Inverse Configuration with Negate
#
# Creating inverse configuration values for symmetric settings

# Security settings with inverses
security:
  # Authentication
  require_authentication: true
  allow_anonymous: (( negate security.require_authentication ))  # false
  
  # Authorization
  strict_permissions: true
  permissive_mode: (( negate security.strict_permissions ))  # false
  
  # SSL/TLS
  force_https: true
  allow_http: (( negate security.force_https ))  # false
  
  # API access
  api_key_required: true
  open_api: (( negate security.api_key_required ))  # false

# Database configuration
database:
  # Connection pooling
  use_connection_pool: true
  single_connection: (( negate database.use_connection_pool ))  # false
  
  # Write modes
  read_only: false
  read_write: (( negate database.read_only ))  # true
  
  # Replication
  use_replicas: true
  primary_only: (( negate database.use_replicas ))  # false
  
  # Transactions
  auto_commit: false
  use_transactions: (( negate database.auto_commit ))  # true

# Caching strategies
caching:
  # Cache enablement
  enabled: true
  disabled: (( negate caching.enabled ))  # false
  
  # Cache behavior
  aggressive_caching: true
  conservative_caching: (( negate caching.aggressive_caching ))  # false
  
  # Cache invalidation
  auto_invalidate: true
  manual_invalidation: (( negate caching.auto_invalidate ))  # false
  
  # Cache warming
  pre_warm_cache: false
  lazy_loading: (( negate caching.pre_warm_cache ))  # true

# Logging configuration
logging:
  # Log levels (inverse relationships)
  verbose_logging: false
  quiet_mode: (( negate logging.verbose_logging ))  # true
  
  # Log destinations
  log_to_file: true
  log_to_console_only: (( negate logging.log_to_file ))  # false
  
  # Log filtering
  include_debug_logs: false
  production_logs_only: (( negate logging.include_debug_logs ))  # true
  
  # Log retention
  compress_logs: true
  keep_uncompressed: (( negate logging.compress_logs ))  # false

# Network settings
network:
  # Connection types
  use_ipv6: true
  ipv4_only: (( negate network.use_ipv6 ))  # false
  
  # Protocols
  use_websockets: true
  polling_only: (( negate network.use_websockets ))  # false
  
  # Load balancing
  sticky_sessions: false
  stateless: (( negate network.sticky_sessions ))  # true
  
  # Timeouts
  use_keepalive: true
  close_immediately: (( negate network.use_keepalive ))  # false

# UI/UX settings
interface:
  # Visual modes
  dark_theme: true
  light_theme: (( negate interface.dark_theme ))  # false
  
  # Density
  compact_mode: false
  spacious_mode: (( negate interface.compact_mode ))  # true
  
  # Animations
  animations_enabled: true
  static_interface: (( negate interface.animations_enabled ))  # false
  
  # Responsiveness
  mobile_optimized: true
  desktop_only: (( negate interface.mobile_optimized ))  # false

# Performance settings
performance:
  # Resource usage
  use_multi_threading: true
  single_threaded: (( negate performance.use_multi_threading ))  # false
  
  # Memory management
  eager_loading: false
  lazy_loading: (( negate performance.eager_loading ))  # true
  
  # Optimization
  optimize_for_speed: true
  optimize_for_memory: (( negate performance.optimize_for_speed ))  # false
  
  # Compilation
  use_jit: true
  interpreted_only: (( negate performance.use_jit ))  # false

# Data handling
data:
  # Compression
  compress_data: true
  store_uncompressed: (( negate data.compress_data ))  # false
  
  # Encryption
  encrypt_at_rest: true
  plaintext_storage: (( negate data.encrypt_at_rest ))  # false
  
  # Validation
  strict_validation: true
  permissive_parsing: (( negate data.strict_validation ))  # false
  
  # Serialization
  use_binary_format: false
  use_text_format: (( negate data.use_binary_format ))  # true

# Development vs Production
deployment:
  # Build types
  production_build: true
  development_build: (( negate deployment.production_build ))  # false
  
  # Optimizations
  minify_code: true
  readable_code: (( negate deployment.minify_code ))  # false
  
  # Debug info
  include_source_maps: false
  stripped_build: (( negate deployment.include_source_maps ))  # true
  
  # Error handling
  show_stack_traces: false
  hide_errors: (( negate deployment.show_stack_traces ))  # true

# Async vs Sync operations
operations:
  # Processing mode
  async_processing: true
  sync_processing: (( negate operations.async_processing ))  # false
  
  # I/O operations
  non_blocking_io: true
  blocking_io: (( negate operations.non_blocking_io ))  # false
  
  # Event handling
  event_driven: true
  polling_based: (( negate operations.event_driven ))  # false
  
  # Execution
  parallel_execution: true
  sequential_execution: (( negate operations.parallel_execution ))  # false