# High concurrency profile - optimized for concurrent processing
version: "1.0"
profile: "high_concurrency"

engine:
  dataflow_order: "breadth-first"
  output_format: "yaml"
  color_output: true
  
  parser:
    strict_yaml: false
    preserve_tags: true
    max_document_size: 10485760  # 10MB

performance:
  enable_caching: true
  enable_parallel: true
  
  cache:
    expression_cache_size: 100000  # Very large cache
    operator_cache_size: 50000
    file_cache_size: 5000
    ttl: "15m"
    enable_warmup: true
  
  concurrency:
    max_workers: 0      # Use all CPUs
    queue_size: 10000   # Large queue
    batch_size: 100     # Large batches
    enable_adaptive: true
  
  memory:
    gc_percent: 300     # Much less frequent GC
    enable_pooling: true
    string_interning: true
  
  io:
    connection_timeout: "30s"
    request_timeout: "60s"
    max_retries: 3
    enable_deduplication: true

logging:
  level: "warn"  # Reduce logging overhead
  format: "text"
  output: "stderr"
  enable_color: true