# Low memory profile - optimized for memory-constrained environments
version: "1.0"
profile: "low_memory"

engine:
  dataflow_order: "breadth-first"
  output_format: "yaml"
  color_output: true
  
  parser:
    strict_yaml: false
    preserve_tags: true
    max_document_size: 1048576  # 1MB limit

performance:
  enable_caching: false  # Disable caching
  enable_parallel: false # Single threaded
  
  cache:
    expression_cache_size: 100
    operator_cache_size: 50
    file_cache_size: 5
    ttl: "30s"
    enable_warmup: false
  
  concurrency:
    max_workers: 1
    queue_size: 10
    batch_size: 1
    enable_adaptive: false
  
  memory:
    max_heap_size: 268435456  # 256MB limit
    gc_percent: 25            # Very frequent GC
    enable_pooling: false     # Disable pooling
    string_interning: false
  
  io:
    connection_timeout: "30s"
    request_timeout: "60s"
    max_retries: 2
    enable_deduplication: false

logging:
  level: "error"  # Minimal logging
  format: "text"
  output: "stderr"
  enable_color: false