#!/bin/bash

cleanup() {
	rm -rf ${TMPDIR}
}

TMPDIR=$(mktemp -d)
trap cleanup QUIT INT EXIT

cat <<EOF > ${TMPDIR}/first.yml
---
first: beginning
EOF

cat <<EOF > ${TMPDIR}/last.yml
---
last: ending
EOF

cp graft ${TMPDIR}
pushd ${TMPDIR}

result=$(echo "first: stdin" | ./graft merge)
[[ ${result} == "first: stdin" ]]

result=$(echo "first: stdin" | ./graft merge -)
[[ ${result} == "first: stdin" ]]

result=$(echo "first: stdin" | ./graft merge first.yml - last.yml)
[[ ${result} == "first: stdin\nlast: ending" ]]

result=$(echo "last: stdin" | ./graft merge first.yml - last.yml)
[[ ${result} == "first: beginning\nlast: ending" ]]

popd
