#!/bin/bash

echo "Bad YAML for 'graft json'"
echo '"3"' | ./graft json
echo

echo "Bad stdin for 'graft json'"
./graft json </dev/null
echo

echo "Bad file for 'graft json'"
./graft json nonexistent.yml
echo; echo

echo "Bad YAML root"
./graft merge assets/json/non-map.yml

echo "Bad File"
./graft merge nonexistent.yml
echo

echo "Bad YAML parsing"
./graft merge assets/json/malformed.yml

echo Recursion Depth
./graft merge assets/dereference/cyclic-data.yml
echo; echo

echo bad merge into non-array
./graft merge assets/merge/first.yml assets/merge/non-array-merge.yml

echo bad merge using keys
./graft merge assets/merge/first.yml assets/merge/error.yml

echo bad merge using keys that don\'t exist
./graft merge assets/merge/first.yml assets/merge/no-key-merge.yml
echo

echo Syntax error
./graft merge assets/concat/fail.yml

echo NotFoundError, TypeMisMatchErrors, all operator errors, all tree errors
./graft merge assets/errors/colortest.yml

exit 0
