on:
  release:
    types: [created]

jobs:
  build-release-artifacts:
    name: build-release-artifacts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - goos: linux
          goarch: amd64
        - goos: linux
          goarch: arm64
        - goos: windows
          goarch: amd64
        - goos: darwin
          goarch: amd64
        - goos: darwin
          goarch: arm64

    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: stable
        check-latest: true

    - name: Build
      env:
        CGO_ENABLED: 0
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: 'go build -v -o graft-${{ matrix.goos }}-${{ matrix.goarch }} -ldflags="-X main.Version=${{ github.event.release.tag_name }}" ./cmd/graft'

    - uses: geofffranks/upload-asset@v2
      with:
        file: ./graft-${{ matrix.goos }}-${{ matrix.goarch }}
        with_sha1: true

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
