on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: stable
          check-latest: true

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go list ./... | grep -v vendor | xargs go test

      - name: Vet
        run: go list ./... | grep -v vendor | xargs go vet

      - name: Build graft binary
        run: go build ./cmd/graft

      - name: Run integration tests with Docker
        run: |
          # Install Perl dependencies (usually pre-installed on Ubuntu)
          sudo apt-get update && sudo apt-get install -y perl
          
          # Make integration script executable
          chmod +x scripts/integration
          
          # Run integration tests
          make integration
